### ISSUE TITLE
Explicitly activated autoindex

### ISSUE THREAD

**Issue by ottowayne** [lasselehtinen/barn#3]
Hi, first of all: Awesome project - thanks for sharing it!

Besides that I was wondering why autoindex is explicitly activated for every nginx vhost since it might pose a security risk.

**Comment by ottowayne** [comment]
I am referring to:
https://github.com/lasselehtinen/barn/blob/5d08f37432ecc5abec7c44d2bf93fd47d513b1a3/roles/webtier/templates/nginx-virtualhost.conf.j2#L13
and
https://github.com/lasselehtinen/barn/blob/5d08f37432ecc5abec7c44d2bf93fd47d513b1a3/roles/webtier/templates/nginx-ssl-virtualhost.conf.j2#L33

**Comment by lasselehtinen** [comment]
Good point. I have now specific reason to keep autoindex on, I guess it is a leftover from old sample configuration. This has been now removed in [this commit](https://github.com/lasselehtinen/barn/commit/589ff55da388f1d33db6b14a2dcc5d3364704a98).

**Comment by ottowayne** [comment]
Alright thanks :+1:
