### ISSUE TITLE
Why apache2?

### ISSUE THREAD

**Issue by Rishats** [lasselehtinen/barn#4]
Hello, i run your vagrant box(ubuntu-test), after all ansible tasks i have apache2. But i need nginx. What should i do?

**Comment by lasselehtinen** [comment]
Seems like they have sneaked apache2 to be running by default in the Ubuntu image. This has been now fixed in the commit below. So please pull the latest version from the repo and try again.

https://github.com/lasselehtinen/barn/commit/664b2210251525c4e77e79fb2eaadde2f8a6120a

**Comment by Rishats** [comment]
Thank you very much, everything works fine!
